name: Release notification
on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/await-npm-package-version-action@v1
        with:
          package: "@octokit/types"
          version: ${{ github.event.release.tag_name }}
      - uses: gr2m/release-notifier-action@v2
        with:
          app_id: ${{ secrets.RELEASE_NOTIFIER_APP_ID }}
          private_key: ${{ secrets.RELEASE_NOTIFIER_APP_PRIVATE_KEY }}
